environment: production

theme: jekyll-theme-primer
url: "https://subtlepurpose.com"

author:
  name: Adrian Teng-Amnuay
  email: pumpadrian@gmail.com

title: subtlepurpose
description: a software development blog focused on devops and cloud infrastructure.

google_analytics: UA-117405938-2
google_adsense: ca-pub-3521905629903035
disqus_forum_name: subtlepurposecom

plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-feed

feed:
  path: atom.xml

exclude: [CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, script]

excerpt_separator: <!--more-->

permalink: pretty

paginate: 5
paginate_path: /page:num/

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    comments: true

images: /assets/img/
