environment: production

theme: jekyll-theme-primer
url: "https://subtlepurpose.com"

author:
  name: Adrian Teng-Amnuay
  email: pumpadrian@gmail.com

title: subtlepurpose
description: A software development blog for cloud and DevOps.

google_analytics: UA-117405938-2
google_adsense: ca-pub-3521905629903035

plugins:
- jekyll-sitemap
- jekyll-paginate

exclude: [CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, script]

permalink: pretty

paginate: 2
paginate_path: /page:num/

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    comments: true
