environment: production

theme: jekyll-theme-midnight
url: "https://tech.adriant.io"

author:
  name: Adrian Teng-Amnuay
  email: pumpadrian@gmail.com

title: tech.adriant.io
description: a software development blog with a focus on devops and cloud infrastructure

google_analytics: UA-117405938-7
google_adsense: 
disqus_forum_name: adriant-io

plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-feed

feed:
  path: atom.xml

exclude: [CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, script]

excerpt_separator: <!--more-->

permalink: pretty

paginate: 5
paginate_path: /page:num/

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    comments: true

images: /assets/img/
