environment: production

theme: jekyll-theme-modernist
url: "https://subtlepurpose.com"

author:
  name: Adrian Teng-Amnuay
  email: pumpadrian@gmail.com

title: subtlepurpose
description: A software development blog focused on DevOps

google_analytics: UA-117405938-2
google_adsense: ca-pub-3521905629903035

plugins:
- jekyll-sitemap
- jekyll-paginate

exclude: [CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, bin]

permalink: /blog/:categories/:year/:month/:day/:title:output_ext

paginate: 3
paginate_path: /blog/page:num/
