environment: production

theme: jekyll-theme-primer
url: "https://tech.adriant.io"

author:
  name: Adrian Teng-Amnuay
  email: pumpadrian@gmail.com

title: technology
description: a software development blog with a focus on devops and cloud infrastructure

google_analytics: UA-117405938-7
google_adsense: 
disqus_forum_name: adriant-io

plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-feed
- jekyll-redirect-from

feed:
  path: atom.xml

exclude: [vendor, .gitignore, Gemfile, Gemfile.lock, bin]

excerpt_separator: <!--more-->

permalink: pretty

paginate: 5
paginate_path: /page:num/

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    comments: true

images: /assets/img/