environment: production

theme: jekyll-theme-modernist
url: "https://subtlepurpose.com"

author:
  name: Adrian Teng-Amnuay
  email: pumpadrian@gmail.com

title: subtlepurpose
description: A DevOps blog

show_downloads: false
google_analytics: UA-117405938-2
google_adsense: ca-pub-3521905629903035

plugins:
- jekyll-sitemap

exclude: [CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

permalink: pretty
